import jsPDF from 'jspdf';
import type { Answer } from '../types';

interface PdfOptions {
  title: string;
  subtitle: string;
  userName: string;
  date: string;
  sections: PdfSection[];
  fileName: string;
}

interface PdfSection {
  title: string;
  answers: Answer[];
}

export function generatePdf(options: PdfOptions) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addPageIfNeeded = (requiredSpace: number) => {
    if (y + requiredSpace > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      y = margin;
      addFooter();
    }
  };

  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by MarketingDoesntWork.com', margin, doc.internal.pageSize.getHeight() - 10);
    doc.text(`Page ${pageCount}`, pageWidth - margin - 20, doc.internal.pageSize.getHeight() - 10);
  };

  // Header
  doc.setFontSize(24);
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.text("MARKETING DOESN'T WORK", pageWidth / 2, y, { align: 'center' });
  y += 12;

  doc.setFontSize(16);
  doc.setTextColor(80);
  doc.setFont('helvetica', 'normal');
  doc.text(options.title, pageWidth / 2, y, { align: 'center' });
  y += 8;

  if (options.subtitle) {
    doc.setFontSize(11);
    doc.text(options.subtitle, pageWidth / 2, y, { align: 'center' });
    y += 8;
  }

  // Meta info
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Prepared for: ${options.userName}`, margin, y);
  y += 5;
  doc.text(`Date: ${options.date}`, margin, y);
  y += 10;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Sections
  for (const section of options.sections) {
    addPageIfNeeded(20);

    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin, y);
    y += 8;

    const sortedAnswers = [...section.answers].sort((a, b) => {
      const aIdx = parseInt(a.questionId.split('_')[1].replace('q', '').replace('f', '')) || 0;
      const bIdx = parseInt(b.questionId.split('_')[1].replace('q', '').replace('f', '')) || 0;
      return aIdx - bIdx;
    });

    for (let i = 0; i < sortedAnswers.length; i++) {
      const answer = sortedAnswers[i];
      addPageIfNeeded(30);

      // Question
      doc.setFontSize(10);
      doc.setTextColor(60);
      doc.setFont('helvetica', 'bold');
      const qLines = doc.splitTextToSize(`Q${i + 1}: ${answer.questionText}`, contentWidth);
      doc.text(qLines, margin, y);
      y += qLines.length * 5 + 3;

      // Answer
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0);
      const aLines = doc.splitTextToSize(answer.answerText || '(No answer provided)', contentWidth);
      for (const line of aLines) {
        addPageIfNeeded(6);
        doc.text(line, margin, y);
        y += 5;
      }
      y += 6;
    }

    y += 4;
  }

  addFooter();

  doc.save(options.fileName);
}

export function generateLevelPdf(level: string, answers: Answer[], userName: string) {
  const levelNames: Record<string, { title: string; subtitle: string; fileName: string }> = {
    '1': {
      title: 'Your Differentiation Discovery Guide',
      subtitle: 'Level 1: Know Yourself, Your Work, and Your Market',
      fileName: `MarketingDoesntWork_Level1_${userName}_${new Date().toISOString().slice(0, 10)}.pdf`,
    },
    '2': {
      title: 'Your Deep ICP Profile',
      subtitle: 'Level 2: Ideal Client Discovery',
      fileName: `MarketingDoesntWork_Level2_${userName}_${new Date().toISOString().slice(0, 10)}.pdf`,
    },
    '3': {
      title: 'Your Content Pillars Guide',
      subtitle: 'Level 3: Content Strategy Discovery',
      fileName: `MarketingDoesntWork_Level3_${userName}_${new Date().toISOString().slice(0, 10)}.pdf`,
    },
  };

  const config = levelNames[level];
  if (!config) return;

  const sections: PdfSection[] = [];

  if (level === '1') {
    sections.push({
      title: 'Know Thyself',
      answers: answers.filter(a => a.sublevel === '1a'),
    });
    sections.push({
      title: 'Know Thy Work',
      answers: answers.filter(a => a.sublevel === '1b'),
    });
    sections.push({
      title: 'Know Thy Market',
      answers: answers.filter(a => a.sublevel === '1c'),
    });
  } else if (level === '2') {
    const fields = answers.filter(a => a.sublevel === 'fields');
    const questions = answers.filter(a => a.sublevel !== 'fields');
    if (fields.length > 0) {
      sections.push({ title: 'Ideal Client Definition', answers: fields });
    }
    sections.push({ title: 'Deep ICP Questions', answers: questions });
  } else {
    sections.push({ title: 'Content Strategy Reflections', answers });
  }

  generatePdf({
    title: config.title,
    subtitle: config.subtitle,
    userName,
    date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    sections,
    fileName: config.fileName,
  });
}

export function generateMasterPdf(allAnswers: Answer[], userName: string, timeInvested: string) {
  const sections: PdfSection[] = [
    {
      title: 'Level 1A: Know Thyself',
      answers: allAnswers.filter(a => a.level === '1' && a.sublevel === '1a'),
    },
    {
      title: 'Level 1B: Know Thy Work',
      answers: allAnswers.filter(a => a.level === '1' && a.sublevel === '1b'),
    },
    {
      title: 'Level 1C: Know Thy Market',
      answers: allAnswers.filter(a => a.level === '1' && a.sublevel === '1c'),
    },
    {
      title: 'Level 2: Ideal Client Definition',
      answers: allAnswers.filter(a => a.level === '2' && a.sublevel === 'fields'),
    },
    {
      title: 'Level 2: Deep ICP Discovery',
      answers: allAnswers.filter(a => a.level === '2' && a.sublevel !== 'fields'),
    },
    {
      title: 'Level 3: Content Strategy Discovery',
      answers: allAnswers.filter(a => a.level === '3'),
    },
    {
      title: 'Final Boss: The Clarity Challenge',
      answers: allAnswers.filter(a => a.level === 'boss'),
    },
  ].filter(s => s.answers.length > 0);

  generatePdf({
    title: 'Your Complete Business Clarity Guide',
    subtitle: `Quest completed in ${timeInvested} | All levels mastered`,
    userName,
    date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    sections,
    fileName: `MarketingDoesntWork_MasterGuide_${userName}_${new Date().toISOString().slice(0, 10)}.pdf`,
  });
}
